dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install pytest unittest2
  - python ./setup.py develop
script: 
  - python3 -m pytest
addons:
  apt:
    packages:
      - build-essential
      - swig
      - libpcsclite-dev
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      python: 3.7
      install: pip install black flake8
      script: 
        - black --check ./emv
        - flake8 ./emv
