name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Set up Python with a specific version
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Spécifiez une version stable de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build  # Ajout de `build` pour une approche moderne

    # Build the distribution files and upload to PyPI
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build  # Utilisation de `build` au lieu de `setup.py`
        twine upload dist/*
